readtogather:
  component: "@sls-next/serverless-component" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    domain:
      - ${env.SUB_DOMAIN}
      - ${env.DOMAIN}
    memory: 1024
